services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3000
    command: pnpm --filter @repo/api dev
    volumes:
      - ./:/app
      - api_node_modules:/app/node_modules
      - api_workspace_node_modules:/app/apps/api/node_modules
    restart: unless-stopped

  personal-app:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.dev
    command: pnpm --filter @repo/personal-app dev
    volumes:
      - ./:/app
      - personal_app_node_modules:/app/node_modules
      - personal_app_workspace_node_modules:/app/apps/personal-app/node_modules
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile.dev
    depends_on:
      - api
      - personal-app

volumes:
  api_node_modules:
  api_workspace_node_modules:
  personal_app_node_modules:
  personal_app_workspace_node_modules:
