packages:
  - apps/*
  - packages/*

allowBuilds:
  '@sentry-internal/node-cpu-profiler': true
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': true
  bcrypt: true
  esbuild: true
  msw: true

catalog:
  '@tailwindcss/vite': ^4.3.1
  '@types/node': ^25.9.3
  '@types/react': ^19.2.17
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^6.0.2
  react: ^19.2.7
  react-dom: ^19.2.7
  react-router-dom: ^7.18.0
  tailwindcss: ^4.3.1
  typescript: ^6.0.3
  vite: ^8.0.16
  zod: ^4.4.3

minimumReleaseAgeExclude:
  - react-router-dom@7.18.0
  - react-router@7.18.0
  - '@sentry/browser-utils@10.59.0'
  - '@sentry/browser@10.59.0'
  - '@sentry/core@10.59.0'
  - '@sentry/feedback@10.59.0'
  - '@sentry/node-core@10.59.0'
  - '@sentry/node@10.59.0'
  - '@sentry/opentelemetry@10.59.0'
  - '@sentry/profiling-node@10.59.0'
  - '@sentry/react@10.59.0'
  - '@sentry/replay-canvas@10.59.0'
  - '@sentry/replay@10.59.0'
  - '@sentry/server-utils@10.59.0'

onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - msw
