packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': latest
  '@types/node': ^25.9.2
  '@types/react': latest
  '@types/react-dom': latest
  '@vitejs/plugin-react': latest
  react: latest
  react-dom: latest
  react-router-dom: latest
  tailwindcss: ^4.3.0
  typescript: latest
  vite: latest
  zod: latest

onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - msw
